### PR TITLE
Added up-to-date stubs

### PR DESCRIPTION
**Pull request by ElTrasho3000**
Exchanged the stubs by Joseph Fergusson (PhonicCanine) with up-to- date stubs. This way it's easier to work with micro:bit V2.

### CODE REVIEW

**Comment by makinteract** [comment]
Can you provide the source from where the stubs come from?

**Comment by ElTrasho3000** [comment]
You can find them here: https://github.com/ElTrasho3000/Microbit-Stubs-Python-Package

It's basically a properly laid out version of oivron's microbit stubs and I implemented the pin hierarchy that you made for Joseph Fergusson's stubs. You can find the links in the readme.

**Comment by makinteract** [comment]
Thank you. Your project is licensed as GNU General Public License v3.0, which is incompatible with the license I chose (MIT). In my understanding, GPLv3 is more restrictive in its usage, and if I were to merge your changes into my project, my project too would automatically be licensed under the GPLv3 instead of my original choice.

I think the best option is to provide in the README a link to your repo (https://github.com/ElTrasho3000/Microbit-Stubs-Python-Package) which also shows how to use the stubs. I would be interested in integrating a version of what you have on a lesser strict license (e.g., MIT). I am going to close this pull request, but if you think you can/want to move your stubs to an MIT license, please feel free to open a new one again and I will be happy to consider a merge.

**Comment by makinteract** [comment]
Following up on my previous comment. I have updated the readme with a link to your project. Again, I would be happy to update the stub library to support v2, but I do not want to make changes to my licensing model (MIT) that would restrict usage for either open-source or proprietary projects.

**Pull request closed without merging**
